services:
  caddy:
    image: ghcr.io/fzymgc-house/caddy-custom:main
    container_name: nas-apps-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - /mnt/apps/nas-caddy-config/Caddyfile:/etc/caddy/Caddyfile:ro
    dns:
      - 172.20.10.5
    networks:
      - default
      - dns
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    name: bridge
    external: true
  dns:
    external: true
    name: dnscrypt-proxy

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
