services:
  caddy:
    image: ghcr.io/fzymgc-house/caddy-custom:main@sha256:705aa89d3925f35369f59457b3cb37b61db19ffb20da64e7b80b73a0c4843505
    container_name: nas-apps-proxy
    hostname: nas-apps-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - /mnt/apps/nas-caddy-config/Caddyfile:/etc/caddy/Caddyfile:ro
    dns:
      - 172.20.10.5
    networks:
      main: {}
      dns:
        ipv4_address: 172.20.10.10
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  main:
    name: main-bridge
    external: true
  dns:
    external: true
    name: dnscrypt-proxy

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
