services:
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.17.1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.rule=Host(`paperless.fzymgc.house`)"
      - "traefik.http.routers.paperless.entrypoints=websecure"
      - "traefik.http.routers.paperless.tls=true"
      - "traefik.http.routers.paperless.tls.certresolver=cloudflare"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
      - "traefik.http.routers.paperless.middlewares=authentik@file"
    depends_on:
      - db
      - valkey
      - tika
      - gotenberg
    volumes:
      - /mnt/paperless-data/data/paperless:/usr/src/paperless/data
      - /mnt/paperless-data/storage/media:/usr/src/paperless/media
      - /mnt/paperless-data/export:/usr/src/paperless/export
      - /mnt/paperless-data/ingestion:/usr/src/paperless/consume
      - /etc/ssl/certs:/etc/ssl/certs:ro
    env_file: .env
    environment:
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: "true"
      PAPERLESS_CONSUMER_RECURSIVE: "true"
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"

      PAPERLESS_REDIS: redis://valkey:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_URL: https://paperless.fzymgc.house
      PAPERLESS_ALLOWED_HOSTS: paperless.fzymgc.house
      PAPERLESS_CORS_ALLOWED_HOSTS: https://paperless.fzymgc.house
      PAPERLESS_TRUSTED_PROXIES: 172.16.0.0/12,192.168.0.0/16,10.0.0.0/8
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
        {
          "openid_connect": {
            "APPS": [
              {
                "provider_id": "authentik",
                "name": "Authentik",
                "client_id": "${PAPERLESS_OIDC_CLIENT_ID}",
                "secret": "${PAPERLESS_OIDC_CLIENT_SECRET}",
                "settings": {
                  "server_url": "https://auth.fzymgc.house/application/o/paperless/.well-known/openid-configuration",
                  "fetch_userinfo": "True",

                }
              },
              "SCOPE": ["openid", "email", "profile", "groups"]
            ],
            "OAUTH_PKCE_ENABLED": "True"
          }
        }      
    networks:
      main:
        aliases:
          - paperless
      internal:
        aliases:
          - paperless

  db:
    image: docker.io/library/postgres:17.6-alpine
    restart: unless-stopped
    volumes:
      - /mnt/paperless-data/data/postgres:/var/lib/postgresql/data
      - ./pg_init.sh:/docker-entrypoint-initdb.d/pg_init.sh
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      internal:
        aliases:
          - db

  valkey:
    image: valkey/valkey:8.1.3-alpine
    restart: unless-stopped
    volumes:
      - /mnt/paperless-data/data/valkey:/data
    networks:
      internal:
        aliases:
          - valkey

  tika:
    image: docker.io/apache/tika:3.2.2.0
    restart: unless-stopped
    networks:
      internal:
        aliases:
          - tika

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.23.0
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      internal:
        aliases:
          - gotenberg

  ai-classifier:
    image: docker.io/clusterzx/paperless-ai:3.0.7
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless-ai-classifier.rule=Host(`paperless.fzymgc.house`) && PathPrefix(`/ai-classifier`)"
      - "traefik.http.routers.paperless-ai-classifier.entrypoints=websecure"
      - "traefik.http.routers.paperless-ai-classifier.tls=true"
      - "traefik.http.routers.paperless-ai-classifier.tls.certresolver=cloudflare"
      - "traefik.http.services.paperless-ai-classifier.loadbalancer.server.port=3000"
      - "traefik.http.routers.paperless-ai-classifier.middlewares=authentik@file"
    restart: unless-stopped
    volumes:
      - /mnt/paperless-data/data/ai-classifier:/data
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      PAPERLESS_API_URL: http://webserver:8000
    networks:
      internal:
        aliases:
          - ai-classifier

networks:
  main:
    name: main-bridge
    external: true
  internal:
    name: internal-bridge
    external: true
