services:
  dns-proxy:
    container_name: dns-proxy
    image: ghcr.io/fzymgc-house/container-dnscrypt-proxy:main@sha256:15120a482cee075ce8f3c6401b9e2b9452d0a61b325b6f9161969473b5fe5712
    ports:
      - 1053:53/udp
      - 1053:53/tcp
    volumes:
      - ./etc:/etc/dnscrypt-proxy:ro
    environment:
      - TZ=US/Eastern
    restart: unless-stopped
    networks:
      main: {}
      dnscrypt-proxy:
        ipv4_address: 172.20.10.5

networks:
  main:
    external: true
    name: main-bridge
  dnscrypt-proxy:
    name: dnscrypt-proxy
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.10.0/25

