services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.karakeep.rule=Host(`karakeep.fzymgc.house`)"
      - "traefik.http.routers.karakeep.entrypoints=websecure"
      - "traefik.http.routers.karakeep.tls=true"
      - "traefik.http.routers.karakeep.tls.certresolver=cloudflare"
      - "traefik.http.services.karakeep.loadbalancer.server.port=3000"
      - "traefik.http.services.karakeep.loadbalancer.server.scheme=http"
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - /mnt/data/nas-container-apps/karakeep/data:/data
      - /etc/ssl/certs:/etc/ssl/certs:ro
    environment:
      MEILI_ADDR: "http://meilisearch:7700"
      BROWSER_WEB_URL: "http://chrome:9222"
      KARAKEEP_ADDRESS: "https://karakeep.fzymgc.house"
      NEXTAUTH_URL: "https://karakeep.fzymgc.house"
      DISABLE_PASSWORD_AUTH: "true"
      OAUTH_WELLKNOWN_URL: "https://auth.fzymgc.house/application/o/karakeep/.well-known/openid-configuration"
      OAUTH_PROVIDER_NAME: authentik
      OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: "true"
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
      DATA_DIR: /data # DON'T CHANGE THIS
    env_file: .env
    networks:
      main:
        aliases:
          - karakeep
      internal:
        aliases:
          - karakeep
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124@sha256:1a0046448e0bb6c275c88f86e01faf0de62b02ec8572901256ada0a8c08be23f
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      main:
        aliases:
          - chrome
      internal:
        aliases:
          - chrome
  meilisearch:
    image: getmeili/meilisearch:v1.19.1@sha256:abab6e9054572fea9fd409cf0f4fe3b65f6c8e70cd0f213004592b6d0e9587ac
    restart: unless-stopped
    command:
      - meilisearch
      - --experimental-dumpless-upgrade
    environment:
      MEILI_NO_ANALYTICS: "true"
    env_file: .env
    volumes:
      - /mnt/data/nas-container-apps/karakeep/meili:/meili_data
    networks:
      main:
        aliases:
          - meilisearch
      internal:
        aliases:
          - meilisearch

networks:
  main:
    name: main-bridge
    external: true
  internal:
    name: internal-bridge
    external: true