services:
  web:
    image: ghcr.io/karakeep-app/karakeep:${KARAKEEP_VERSION:-release}
    restart: unless-stopped
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - /mnt/data/karakeep/data:/data
      - /etc/ssl/certs:/etc/ssl/certs:ro
    ports:
      - 3000:3000
    environment:
      MEILI_ADDR: "http://meilisearch:7700"
      BROWSER_WEB_URL: "http://chrome:9222"
      KARAKEEP_ADDRESS: "https://karakeep.fzymgc.house"
      NEXTAUTH_URL: "https://karakeep.fzymgc.house"
      DISABLE_PASSWORD_AUTH: "true"
      OAUTH_WELLKNOWN_URL: "https://auth.fzymgc.house/application/o/karakeep/.well-known/openid-configuration"
      OAUTH_PROVIDER_NAME: authentik
      OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: "true"
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
      DATA_DIR: /data # DON'T CHANGE THIS
    env_file: .env
    networks:
      main:
        aliases:
          - karakeep
      internal:
        aliases:
          - karakeep
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124@sha256:1a0046448e0bb6c275c88f86e01faf0de62b02ec8572901256ada0a8c08be23f
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      internal:
        aliases:
          - chrome
  meilisearch:
    image: getmeili/meilisearch:v1.15.2@sha256:fe500cf9cca05cb9f027981583f28eccf17d35d94499c1f8b7b844e7418152fc
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
    env_file: .env
    volumes:
      - /mnt/data/karakeep/meili:/meili_data
    networks:
      internal:
        aliases:
          - meilisearch

networks:
  main:
    name: main-bridge
    external: true
  internal:
    name: internal