services:
  searxng:
    image: docker.io/searxng/searxng:latest@sha256:d7325ed72795844fd8cbbba552e19a4fa60c7750606ece793e338bc2dc87e5d7
    hostname: searxng
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.rule=Host(`searxng.fzymgc.house`)"
      - "traefik.http.routers.searxng.entrypoints=websecure"
      - "traefik.http.routers.searxng.tls=true"
      - "traefik.http.routers.searxng.tls.certresolver=cloudflare"
      - "traefik.http.services.searxng.loadbalancer.server.port=8080"
    environment:
      TZ: US/Eastern
      SEARXNG_BASE_URL: https://searxng.fzymgc.house
      INSTANCE_NAME: fzymgc-house
      SEARXNG_SECRET: "bb31a4e72ccbd0adaf9e88b510501afe5269d593fdb9a346271721cf85b8b331"
      SEARXNG_IMAGE_PROXY: true
      SEARXNG_PUBLIC_INSTANCE: false
      SEARXNG_LIMITER: true
      SEARXNG_VALKEY_URL: valkey://valkey:6379/0
    volumes:
      - /mnt/data/nas-container-apps/searxng/etc:/etc/searxng
      - ./settings.yml:/etc/searxng/settings.yml
    networks:
      main-bridge:
        aliases:
          - searxng
      internal-bridge:
        aliases:
          - searxng
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
  valkey:
    image: valkey/valkey:latest@sha256:a137a2b60aca1a75130022d6bb96af423fefae4eb55faf395732db3544803280
    volumes:
      - /mnt/data/nas-container-apps/searxng/valkey:/data
    networks:
      internal-bridge:
        aliases:
          - valkey
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
networks:
  main-bridge:
    name: main-bridge
    external: true
  internal-bridge:
    name: internal

