services:
  searxng:
    image: docker.io/searxng/searxng:latest
    hostname: searxng
    environment:
      TZ: US/Eastern
      BASE_URL: https://searxng.fzymgc.house
      INSTANCE_NAME: fzymgc-house
      SEARXNG_SECRET: "bb31a4e72ccbd0adaf9e88b510501afe5269d593fdb9a346271721cf85b8b331"
      SEARXNG_IMAGE_PROXY: true
      SEARXNG_PUBLIC_INSTANCE: false
      SEARXNG_LIMITER: true
      SEARXNG_REDIS_URL: redis://redis:6379
    volumes:
      - /mnt/apps/searxng/etc:/etc/searxng
    networks:
      main: {}
      internal: {}
  redis:
    image: valkey/valkey:latest
    ports:
      - 6379:6379
    volumes:
      - /mnt/apps/searxng/redis:/data
    networks:
      - internal

networks:
  main:
    name: main-bridge
    external: true
  internal:
    name: internal

