services:
  searxng:
    image: docker.io/searxng/searxng:latest@sha256:8f1196f03960ebae2292ba7b6d3e074c643abded31ad5bb0d0e971e20670156c
    hostname: searxng
    environment:
      TZ: US/Eastern
      BASE_URL: https://searxng.fzymgc.house
      INSTANCE_NAME: fzymgc-house
      SEARXNG_SECRET: "bb31a4e72ccbd0adaf9e88b510501afe5269d593fdb9a346271721cf85b8b331"
      SEARXNG_IMAGE_PROXY: true
      SEARXNG_PUBLIC_INSTANCE: false
      SEARXNG_LIMITER: true
      SEARXNG_REDIS_URL: redis://redis:6379
    volumes:
      - /mnt/apps/searxng/etc:/etc/searxng
    ports:
      - "29999:8080"
    networks:
      main:
        aliases:
          - searxng
      internal:
        aliases:
          - searxng
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
  redis:
    image: valkey/valkey:latest@sha256:facc1d2c3462975c34e10fccb167bfa92b0e0dbd992fc282c29a61c3243afb11
    volumes:
      - /mnt/data/searxng/redis:/data
    networks:
      internal:
        aliases:
          - redis
          - valkey
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
networks:
  main:
    name: main-bridge
    external: true
  internal:
    name: internal

